In [1]:
import pandas as p 

In [2]:
import numpy as n

In [3]:
import warnings 

In [4]:
warnings.filterwarnings("ignore")

In [5]:
#Load given dataset 
data = p.read_csv('fake_job_postings.csv') 

In [6]:
df=data.dropna()

In [7]:
df.columns 

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder 

In [9]:
var_mod = ['job_id', 'title', 'location', 'department', 'salary_range', 
'company_profile', 'description', 'requirements', 'benefits', 
'telecommuting', 'has_company_logo', 'has_questions', 'employment_type', 
'required_experience', 'required_education', 'industry', 'function', 
'fraudulent']

In [10]:
le = LabelEncoder()

In [11]:
for i in var_mod: 
    df[i] = le.fit_transform(df[i]).astype(int)

In [13]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set. 
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef, cohen_kappa_score, accuracy_score, average_precision_score, roc_auc_score 

In [14]:
X = df.drop(labels='fraudulent', axis=1) 

In [15]:
#Response variable 
y = df.loc[:,'fraudulent']

In [16]:
#We'll use a test size of 30%. We also stratify the split on the response variable, which is very important to do because there are so few fraudulent transactions. 

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y) 

In [19]:
from sklearn.cluster import KMeans 

In [20]:
kmeans = KMeans(n_clusters=2, random_state=0)

In [21]:
kmeans.fit(X_train,y_train) 

KMeans(n_clusters=2, random_state=0)

In [22]:
predictR = kmeans.predict(X_test) 

In [23]:
print("") 

In [24]:
x = (accuracy_score(y_test,predictR)*100) 

In [25]:
print('Accuracy result of kmeans is:', x) 

Accuracy result of kmeans is: 54.93562231759657


In [26]:
print("")

In [27]:
print('Classification report of kmeans Results:')

Classification report of kmeans Results:


In [29]:
print('Classification report of kmeans Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xkm = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR) 
print('Confusion Matrix result of kmeans is:\n', confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1) 

Classification report of kmeans Results:

              precision    recall  f1-score   support

           0       0.96      0.52      0.68       211
           1       0.15      0.82      0.26        22

    accuracy                           0.55       233
   macro avg       0.56      0.67      0.47       233
weighted avg       0.89      0.55      0.64       233

Confusion Matrix result of kmeans is:
 [[110 101]
 [  4  18]]

Sensitivity :  0.5213270142180095

Specificity :  0.8181818181818182


In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
rfc = RandomForestClassifier() 
rfc.fit(X_train,y_train) 
predictR = rfc.predict(X_test) 
print("")

In [33]:
x = (accuracy_score(y_test,predictR)*100) 
print('Accuracy result of Random Forest: is:', x)

Accuracy result of Random Forest: is: 97.42489270386267


In [34]:
print('Classification report of Random Forest: Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xrf = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR) 
print('Confusion Matrix result of Random Forest: is:\n', confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1)

Classification report of Random Forest: Results:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       211
           1       0.94      0.77      0.85        22

    accuracy                           0.97       233
   macro avg       0.96      0.88      0.92       233
weighted avg       0.97      0.97      0.97       233

Confusion Matrix result of Random Forest: is:
 [[210   1]
 [  5  17]]

Sensitivity :  0.995260663507109

Specificity :  0.7727272727272727


In [35]:
from sklearn.svm import SVC 

In [36]:
s = SVC() 
s.fit(X_train,y_train) 
predictR = s.predict(X_test) 
print("") 

In [37]:
x = (accuracy_score(y_test,predictR)*100) 
print('Accuracy result of Support Vector Machines is:', x) 
print("") 
print("")

Accuracy result of Support Vector Machines is: 90.55793991416309




In [38]:
print('Classification report of Support Vector Machines: Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xs = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR) 
print('Confusion Matrix result of Support Vector Machines: is:\n', 
confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1) 

Classification report of Support Vector Machines: Results:

              precision    recall  f1-score   support

           0       0.91      1.00      0.95       211
           1       0.00      0.00      0.00        22

    accuracy                           0.91       233
   macro avg       0.45      0.50      0.48       233
weighted avg       0.82      0.91      0.86       233

Confusion Matrix result of Support Vector Machines: is:
 [[211   0]
 [ 22   0]]

Sensitivity :  1.0

Specificity :  0.0


In [39]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 
gnb.fit(X_train,y_train) 
predictR = gnb.predict(X_test) 
print("") 
x = (accuracy_score(y_test,predictR)*100) 
print('Accuracy result of Naive bayes is:', x)


Accuracy result of Naive bayes is: 86.69527896995707


In [40]:
print('Classification report of Naive bayes: Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xnb = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR) 
print('Confusion Matrix result of Naive bayes: is:\n', confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1)

Classification report of Naive bayes: Results:

              precision    recall  f1-score   support

           0       0.93      0.92      0.93       211
           1       0.32      0.36      0.34        22

    accuracy                           0.87       233
   macro avg       0.63      0.64      0.63       233
weighted avg       0.87      0.87      0.87       233

Confusion Matrix result of Naive bayes: is:
 [[194  17]
 [ 14   8]]

Sensitivity :  0.919431279620853

Specificity :  0.36363636363636365


In [41]:
from sklearn.tree import DecisionTreeClassifier 
dtree = DecisionTreeClassifier() 
dtree.fit(X_train,y_train) 
predictR = dtree.predict(X_test) 
print("")

In [42]:
x = (accuracy_score(y_test,predictR)*100) 
print('Accuracy result ofDecision Tree Classifier  is:', x)

Accuracy result ofDecision Tree Classifier  is: 94.84978540772532


In [43]:
print('Classification report of Decision Tree Classifier : Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xd = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR) 
print('Confusion Matrix result of Decision Tree Classifier : is:\n', 
confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1) 

Classification report of Decision Tree Classifier : Results:

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       211
           1       0.67      0.91      0.77        22

    accuracy                           0.95       233
   macro avg       0.83      0.93      0.87       233
weighted avg       0.96      0.95      0.95       233

Confusion Matrix result of Decision Tree Classifier : is:
 [[201  10]
 [  2  20]]

Sensitivity :  0.95260663507109

Specificity :  0.9090909090909091


In [44]:
from sklearn.linear_model import LogisticRegression 
logR= LogisticRegression() 
logR.fit(X_train,y_train) 
predictR = logR.predict(X_test) 
print("") 
x = (accuracy_score(y_test,predictR)*100) 
print('Accuracy result of Logistic Regression is:', x) 


Accuracy result of Logistic Regression is: 90.55793991416309


In [48]:
print('Classification report of Logistic Regression : Results:') 
print("") 
print(classification_report(y_test,predictR)) 
xl = (accuracy_score(y_test,predictR)*100) 
cm2=confusion_matrix(y_test,predictR)
print('Confusion Matrix result of Logistic Regression : is:\n', confusion_matrix(y_test,predictR)) 
print("") 
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1]) 
print('Sensitivity : ', sensitivity1 ) 
print("") 
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1]) 
print('Specificity : ', specificity1) 

Classification report of Logistic Regression : Results:

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       211
           1       0.50      0.18      0.27        22

    accuracy                           0.91       233
   macro avg       0.71      0.58      0.61       233
weighted avg       0.88      0.91      0.89       233

Confusion Matrix result of Logistic Regression : is:
 [[207   4]
 [ 18   4]]

Sensitivity :  0.981042654028436

Specificity :  0.18181818181818182
